### PR TITLE
New content: Fortran

### PR DESCRIPTION
**Pull request by szaghi**
Add new content: Fortran
    
 Add new content *fortran* and initialized with the first tip: how to implement a dynamically varying length string. Very short tips to initialize and use a varying length string are provided.

### CODE REVIEW

**Comment by tbodt** [comment]
Just curious about this: What use does Fortran have today?

**Comment by szaghi** [comment]
This is a common preconception. Fortran is presently the best programming language for scientific applications, hpc, parallel computing, etc...

The performances of Fortran code are better (in general) than C counterparts. This high performances and easy in *formula* translate come with some cons (unflexibility, limited support to OOP, etc...): no one will write an OS in Fortran, but if you want to perform scientific computations with the highest performances the best is Fortran. Even better than C... because the Fortran compilers are written in C:-)

These are just the main reasons. Anyhow, Fortran is presently one of most used languages in the world... there are code of 1960' running... the available libraries are huge!

**Comment by tbodt** [comment]
Good to know. Thanks.

**Comment by szaghi** [comment]
You are welcome. See you soon.

Il giorno 21:48 mar 03/feb/2015 Theodore Dubois <notifications@github.com>
ha scritto:

**Comment by mike-burns** [comment]
This repo isn't for tips, it's for things you learned today. Did you learn this today?

**Comment by tbodt** [comment]
@mike-burns What's the difference?

**Comment by szaghi** [comment]
No, I do not learn it today... Last weak is too old? sorry, I stop kidding.
Maybe, I do not understand the aim of til: I have assumed that the goal is
to collect uncommon or new tips that are difficult to learn in the standard
ways (guides, tutorials...). If I am wrong I am very sorry.

My best regards
Il 04/feb/2015 01:03 "Mike Burns" <notifications@github.com> ha scritto:

**Comment by JoelQ** [comment]
Closing this since it is more of a tutorial/blog post than a quick tip

**Pull request closed without merging**
