### PR TITLE
Adds brief explanation to be careful with --force

### PR DESCRIPTION
**Pull request by lmatiolis**

### CODE REVIEW

**Comment by mike-burns** [comment]
The git-push(1) manpage already says "use it with care". This PR doesn't seem to add anything that you have learned today.

**Comment by lmatiolis** [comment]
@mike-burns I was just thinking that people from all different knowledge levels will be reading these TILs and i thought it would be important to give some advice on the risk of doing this without knowing exactly what you are doing. A word of caution is always good in my opinion and i was hoping to avoid something like: "Today i learned that doing a rebase in a remote branch can cause a serious mess".

**Comment by awestroke** [comment]
I definitely think that any mention of `git push --force` should have a big warning attached
:+1:

**Comment by JoelQ** [comment]
@seanpdoyle thoughts? You wrote the original TIL.

**Comment by seanpdoyle** [comment]
@JoelQ @lmatiolis I wrote this TIL while working on and reorganizing a branch in isolation. 

I like the idea of mentioning that collaborators will have the rug pulled out from under them, since it isn't some I had considered originally.

I'm just not sure about the wording.

How do you feel about something like

> BEWARE: Be sure to mention to others collaborating on this branch that you're rewriting its history.

**Comment by lmatiolis** [comment]
@seanpdoyle I like the idea of "BEWARE" and communicating with people on the team about the rebase you did in a remote branch. The problem i see with saying only that is that it passes an idea of everything is fine if people know about the rebase you did. Which is not exactly true. You are going to create problems, since they might have already based some work on your old commits that got rebased and that might even introduce the commits you rebased again in the repository. There is an example showing what can happen here: http://git-scm.com/book/en/v2/Git-Branching-Rebasing#The-Perils-of-Rebasing

Maybe we could mix the two phrases for a more complete warning?

**Comment by seanpdoyle** [comment]
@lmatiolis good points!

I encourage you to draft something up that you feel covers all those bases.

**Comment by lmatiolis** [comment]
@seanpdoyle What do you think of this:

>BEWARE: Do this with caution if you are not the only person working on this branch.
The branch history can turn into a mess if people based their work on commits that are now gone because of the rebase you did. For example, collaborators could push again the commits you removed from the repository, since they would still have them in their local repository.
If you really need to do a rebase on a remote branch that others are working, please remember to communicate the team. This way they will not be caught unguarded in the middle of a mess and can act accordingly to keep the history clean.

**Comment by mike-burns** [comment]
How about linking `--force` to the git-push(1) documentation, which already says all of this, and which people should read before copying and pasting text from a Web page anyway?

**Comment by lmatiolis** [comment]
@mike-burns I don't think putting a link to the documentation is the only thing to do here. If that was the case, we should just erase this TIL and put a link to the documentation of rebase, no? It would be more complete and people would be reading the official source, plus extra info.

But i think this kills the purpose of this repository, no?

Don't get me wrong, i agree that people should always read the documentation of something they are going to use. But if we are aiming to provide good TIL texts, we can't expect that everyone will go search for more info on the web. When people read something from a trusted source, they believe all important information is there (although some might be missing).

Anyway, my suggestion is that we should add an explanation and if we want to guide the reader to find more about the issue, we add the documentation link too.

**Comment by dideler** [comment]
I don't think people should execute commands (especially when it's rewriting history) without understanding what they do. And I think the onus is on the reader to understand the risks of force pushing.

But if the decision is to add a warning, I think the current suggestion is too fear-inducing (too many people are already scared of misusing Git). 

Here's a suggestion that doesn't say to avoid it, but instead to use it with care:
> **Caution:** Force pushing can cause the remote repository to lose commits. Use it with care, especially when you are not the only person working on the branch.

**Comment by tejasbubane** [comment]
I think Scott Chacon's wording "Do not rebase commits that are already pushed to a public repository." is very accurate. I have created a pull request at #54, did not notice this one already existed.

**Comment by dideler** [comment]
@tejasbubane following that advice will definitely simplify this TIL and keep a neutral stance about force pushing which is :+1: IMO.

Change 
>  Keep in mind that you might have to force push your branch to `origin`,
 depending on whether or not your revised commits have been pushed.
 
     $ git push origin my-branch-name --force

to just

     $ git push origin my-branch-name

If the reader is trying to edit pushed history is not really relevant to the TIL.

**Comment by tejasbubane** [comment]
@dideler That will be fine as well :+1:

**Comment by seanpdoyle** [comment]
@dideler I'm most in favor of that solution.

**Comment by tejasbubane** [comment]
I have updated my pull request #54 as per @dideler's suggestion.

**Comment by lmatiolis** [comment]
@dideler Good solution! :+1: 

This way, if the reader needs to use --force, he will have to search for more information!

Should i just remove the explanation and the --force option, and add a small phrase so the `push` doesn't seem detached from the rest of the text? Something like:

Change:
> Keep in mind that you might have to force push your branch to origin,
depending on whether or not your revised commits have been pushed.
` $ git push origin my-branch-name --force `

To:
> Then, just push your branch to origin.
` $ git push origin my-branch-name `

**Comment by lmatiolis** [comment]
Sorry @tejasbubane, i didn't see you changing your PR.

**Comment by dideler** [comment]
@JoelQ I think that's the best solution :grinning:

**Comment by JoelQ** [comment]
@seanpdoyle Can this be closed?

**Pull request closed without merging**
