### PR TITLE
power of plus operator

### PR DESCRIPTION
**Pull request by aforloney**
This is a trivial example of the flexibility of a loosely typed
languages where you can apply the concatentation operator of two
different types (ie, object and array) to produce an entirely different
type.

### CODE REVIEW

**Comment by nightscape** [comment]
I would much rather term this "Pitfalls of the plus operator" (see also https://www.destroyallsoftware.com/talks/wat)

**Comment by posixpascal** [comment]
+1 for „Pitfalls of the plus operator“.

Also you could explain why ([] + {}) equals [object Object]. The + operator doesn’t know how to add an Array and an Object and runs the .toString() method on both operands. Since [].toString() equals an empty string and {}.toString() equals [object Object] you get the result.


Am 28. Januar 2015 bei 11:26:12, Martin Mauch (notifications@github.com) schrieb:

I would much rather term this "Pitfalls of the plus operator" (see also https://www.destroyallsoftware.com/talks/wat)

**Comment by aforloney** [comment]
I had made the requested changes for this pull request. Mind glancing it over and letting me know your thoughts?

**Comment by nightscape** [comment]
:+1:

**Comment by posixpascal** [comment]
:+1:

**Comment by JoelQ** [comment]
Although rather cool, this is super arcane and not useful. As such, I don't think it fits in TIL. I'm going to close this.

**Pull request closed without merging**
