### PR TITLE
TIL: Search&Replace in multiple files

### PR DESCRIPTION
**Pull request by andreabadesso**

### CODE REVIEW

**Comment by zamith** [comment]
@andreabadesso Have you given a look at [Greplace](https://github.com/skwp/greplace.vim)?

**Comment by andreabadesso** [comment]
I hadn't! Will test it, thank you

**Comment by JoelQ** [comment]
I've had a lot of success with Greplace. However, I like your step-by-step walkthrough of the pure Vim approach using buffers :+1:

**Comment by JoelQ** [comment]
Merged as https://github.com/thoughtbot/til/commit/58dbf31a17e369e4d3ce0533ecaaa271f10d7add

**Comment by andreabadesso** [comment]
:+1:

**Pull request closed without merging**
