### PR TITLE
added osx directory for til catagory & batch rename post

### PR DESCRIPTION
**Pull request by ThoughtbotThom**

### CODE REVIEW

**Comment by kenyonj** [comment]
:+1:

**Comment by mike-burns** [comment]
When adding a new category, be sure to update the list of topics in the README (at least until #11 is merged).

**Comment by mike-burns** [comment]
#11 is now merged, so this looks good to go.

**Comment by ThoughtbotThom** [comment]
crap; my last update added osx to toc!

**Pull request merged**
