### PR TITLE
Two ways of squashing commits

### PR DESCRIPTION
**Pull request by teoljungberg**
Credits to @iancanderson for pointing this out for me

### CODE REVIEW

**Comment by vohof** [comment]
This is for the guy merging the PR or the guy submitting a PR?

**Comment by dideler** [comment]
This repository is great, I'm learning new things every day :grinning:

**Comment by tbodt** [comment]
Slight syntax error: The closing ``` is on the same line as the code, so the next paragraph gets treated as code. It should be on a new line.

**Comment by JoelQ** [comment]
Looks good to me! Merge and buffer at your discretion.

**Pull request merged**
