### PR TITLE
Javascript / Lesser known features of the console.api

### PR DESCRIPTION
**Pull request by jucrouzet**
We've all used the console tools for age but most of use only use the basic features like console.log() or console.error().

However, the console API is really powerful and offers a lot of very interesting features.

### CODE REVIEW

**Comment by tbodt** [comment]
The word I think you mean is "unknown" or "less well known", not "misknown".

**Comment by xcambar** [comment]
@tbodt Agreed. "Lesser known" maybe?

**Comment by jucrouzet** [comment]
Yep, sorry I'm french ... I used the wrong word, I translated 'méconnu' (Not well known to the general public) to misknown, (prefix 'mé' is gerally translated to 'mis').
I will use "lesser known".

**Comment by tbodt** [comment]
All the image links are broken. It's because the image paths that don't start with `/` are not relative to the current Markdown document, but relative the repository root. So, for example, you'd have to replace `console_misknown_features/group.png` with `javascript/console_misknown_features/group.png`. And fix "misknown" there, too.

**Comment by jucrouzet** [comment]
Nope, using  `javascript/console_lesser_known_features/group.png` renders as : 
https://github.com/jucrouzet/til/raw/6f1879c1d52b69c8dcc230fd8b8bd15705182f86/javascript/javascript/console_lesser_known_features/group.png 
So path not starting with `/` **are** relative to the current MD doc's path.

**Comment by jucrouzet** [comment]
Yup, it's correctly rendered, with images :
https://github.com/jucrouzet/til/blob/b024a15bd58cda05f5c7c16d26dea00b4f081772/javascript/console_lesser_known_features.md

**Comment by jucrouzet** [comment]
So, off topic ?

**Comment by pirj** [comment]
I like that. It's brief, useful and practical.

**Comment by jucrouzet** [comment]
@JoelQ I've read the TIL guidelines PR, so, I think that this TIL is a bit too long no ?

Should I cancel this PR ?

**Comment by JoelQ** [comment]
@jucrouzet You have some good content here! However, it doesn't really fit the format of TIL. A TIL is a quick tip that you've recently learned, not a complete article on a subject. You should definitely consider publishing this as a blog post somewhere though.

**Comment by jucrouzet** [comment]
Yep, did it : https://medium.com/p/javascript-console-lesser-known-features-9fe3852ce48b

I will close the PR so.

**Pull request closed without merging**
