### PR TITLE
TIL about BasicObject

### PR DESCRIPTION
**Pull request by terrellt**
BasicObject lets you create a class without Kernel methods.

### CODE REVIEW

**Comment by croaky** [comment]
Nice one, @terrellt. Thanks! @JoelQ Do you want to take the lead on squashing and merging this one?

**Comment by JoelQ** [comment]
@terrellt :+1: I didn't know that!

@croaky will squash and merge

**Comment by JoelQ** [comment]
Merged in  2bf7d51b45

I'm going to buffer a tweet. @terrellt, we'd like to credit you for this tip. What is you twitter handle?

**Comment by terrellt** [comment]
@terrell_dt. Thanks for the merge!

**Pull request closed without merging**
