### PR TITLE
Exceptions Raised by `find_by` vs. `find`

### PR DESCRIPTION
**Pull request by GolfyMcG**

### CODE REVIEW

**Comment by jarinudom** [comment]
The same applies to dynamic finders as of Rails 4.x (i.e. `find_by_name` vs `find_by_name!`).

**Comment by GolfyMcG** [comment]
@jarinudom - yeah, we've specifically avoided the dynamic `find_by` methods due to their [mild deprecation](http://api.rubyonrails.org/classes/ActiveRecord/Base.html#class-ActiveRecord::Base-label-Dynamic+attribute-based+finders). You are absolutely right though.

**Comment by GolfyMcG** [comment]
@jarinudom  - updated to include the dynamic finders (with a mention of the ActiveRecord docs on deprecation).

**Comment by jarinudom** [comment]
:+1:

**Comment by jrhorn424** [comment]
Is the proper usage of `find_by!` and `find_by` obvious when *not* looking up by `id`? If not, I'd add another example.

```ruby
ObjectModel.find_by!(name: "foo") # use only when exceptions should be raised
ObjectModel.find_by!(name: "foo") # use when exceptions should be surpressed
```

**Comment by GolfyMcG** [comment]
@jrhorn424 - updated to include the more general example!

**Comment by jrhorn424** [comment]
:+1:

**Comment by JoelQ** [comment]
Thanks for contributing @GolfyMcG ! I've merged this as ca1927dfecc4043ca9aabce8bd60b68a202a68da . I'd like to credit you when we tweet this learning, what is your twitter handle?

**Comment by GolfyMcG** [comment]
@JoelQ my twitter handle is [GolfyMcG](https://twitter.com/GolfyMcG)

**Comment by GolfyMcG** [comment]
and thank you!

**Pull request closed without merging**
