### PR TITLE
Update all-but-the-first-element-from-array.md

### PR DESCRIPTION
**Pull request by jrhorn424**
Illustrate discarded value and splat.

### CODE REVIEW

**Comment by jrhorn424** [comment]
Apologies. This is already covered in https://github.com/thoughtbot/til/blob/master/ruby/parallel-assignment.md but might bear repeating?

**Comment by JoelQ** [comment]
This suggestion is quite popular! It's already come up in:

* #32 
* #20 
* #19 

Thoughts on just adding a link at the bottom to the parallel assignment TIL?

**Comment by mike-burns** [comment]
Is this a thing that you learned today, or a piece of knowledge that you wish to demonstrate but which you already knew?

**Comment by jrhorn424** [comment]
I didn't learn it that day, but learned recently (within the last few weeks). I believe I saw it when I was digging around in an FP library for ruby.

**Comment by JoelQ** [comment]
I'm going to close this since it is a duplicate.

**Pull request closed without merging**
