### PR TITLE
Add example using Ruby syntax

### PR DESCRIPTION
**Pull request by jgn**

### CODE REVIEW

**Comment by croaky** [comment]
@jgn Good to see your name and face! Hope things are well in Minnesota.

@majjoha had the same idea in https://github.com/thoughtbot/til/pull/19. That version has it in a different spot in the file and uses `head` and `tail` instead of `_` and `rest_of_list`. I like both versions for showing different conventions. @JoelQ what do you think!?

**Comment by jirutka** [comment]
The version proposed in #19 is IMHO much cleaner and better explained.

**Comment by jgn** [comment]
Fair enough - I didn't see #19 -- oops. I think it is worth mentioning, though, that this is done with Ruby and leverages the syntax. It might be worth putting it at the very top since as I point out there are no dependencies on library code.

Additionally, the reason for outlining these cases are rather under motivated: When would you not want the "head"?

**Comment by jirutka** [comment]
> I think it is worth mentioning, though, that this is done with Ruby and leverages the syntax.

Probably I don’t understand your point, but isn’t that obvious from the code?

> When would you not want the “head?”

Then you can, obviously, just ignore the `head` variable. Underscore is nothing special in Ruby, it’s just a convenient name for a variable that you don’t care about, but it can by named `foo`, `head` or `dont_care` and it’s exactly the same.

**Pull request closed without merging**
