### PR TITLE
First and rest elements from Ruby array

### PR DESCRIPTION
**Pull request by Baltazore**
via http://devblog.avdi.org/2010/01/31/first-and-rest-in-ruby/

### CODE REVIEW

**Comment by JoelQ** [comment]
@Baltazore thanks for sharing! I believe this is a duplicate of https://github.com/thoughtbot/til/blob/master/ruby/parallel-assignment.md

**Comment by Baltazore** [comment]
@JoelQ thanks for pointing to this file. I missed it. I'll close this now.

**Comment by oversee-jromer** [comment]
The following would be a useful addition to https://github.com/thoughtbot/til/blob/master/ruby/parallel-assignment.md

```
zero = []
one  = [0]
many = [0,1,2,3,4]
```

```
first, *rest = *zero
first                           # => nil
rest                            # => []
first, *rest = *one    
first                           # => 0
rest                            # => []
first, *rest = *many        
first                           # => 0
rest                            # => [1, 2, 3, 4]
```

**Comment by Baltazore** [comment]
@oversee-jromer this file https://github.com/thoughtbot/til/blob/master/ruby/parallel-assignment.md already contains some useful examples, so I think it's not needed.

**Comment by muescha** [comment]
i think the zero/one/many shows all edge cases 

thats why: +1 from me for the addition (can be combined with the existing samples)

**Pull request closed without merging**
